const FETCH_PRODUCTS = "FETCH_PRODUCTS"
const ACTIVATE_GRID_VIEW = "ACTIVATE_GRID_VIEW"
const ACTIVATE_LIST_VIEW = "ACTIVATE_LIST_VIEW"
const UPDATE_FILTERS = "UPDATE_FILTERS"
const FILTER_PRODUCTS = "FILTER_PRODUCTS"
const CLEAR_FILTERS = "CLEAR_FILTERS"

export {
  FETCH_PRODUCTS,
  ACTIVATE_GRID_VIEW,
  ACTIVATE_LIST_VIEW,
  UPDATE_FILTERS,
  FILTER_PRODUCTS,
  CLEAR_FILTERS,
}
